### ISSUE TITLE
Support new csproj format

### ISSUE THREAD

**Issue by danspam** [sboulema/FluentMigratorRunner#1]
This appears to only support the old style csproj projects. If you right click on any project using the new sdk format (.net core style) then no Fluent Migrator menu item appears.

Is there any way to support both project styles?

**Comment by sboulema** [comment]
Please try the new release (1.1.12) https://github.com/sboulema/FluentMigratorRunner/releases/tag/v1.1.12

**Comment by danspam** [comment]
That works a treat, thanks.
